services:
  mongo:
    image: mongo:6.0
    container_name: covid_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: covid_api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./shared/config/.env
    depends_on:
      - mongo

  dash:
    build:
      context: .
      dockerfile: dash/Dockerfile
    container_name: covid_dash
    restart: always
    ports:
      - "8050:8050"
    env_file:
      - ./shared/config/.env
    depends_on:
      - api

volumes:
  mongo_data:
