# config.py
EXCESS_MORTALITY_PAGE = "excess-mortality"
VACCINATION_PAGE = "vaccinations"
INFECTION_CASES_PAGE = "infection-cases"
INFECTION_DEATHS_PAGE = "infection-deaths"
DASHBOARDS_LIST = [EXCESS_MORTALITY_PAGE, VACCINATION_PAGE,INFECTION_CASES_PAGE,INFECTION_DEATHS_PAGE]
API_BASE = "http://127.0.0.1:5000"
