-- setup.sql
-- Run as ACCOUNTADMIN (trial) in AWS Ohio (us-east-2) region account.

-- 1) RESOURCE MONITOR (monthly and daily, notify at 75%, suspend at 85%, suspend_immediate at 95%)
-- montly rm is used for the account, daily rm is used for the warehouse
CREATE OR REPLACE RESOURCE MONITOR RM_BUDGET_MONTHLY
  WITH CREDIT_QUOTA = 350
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 75 PERCENT DO NOTIFY
           ON 85 PERCENT DO SUSPEND
           ON 95 PERCENT DO SUSPEND_IMMEDIATE;
-- Assign the resource monitor to the account
ALTER ACCOUNT SET RESOURCE_MONITOR = 'RM_COVID_MONTLY';

CREATE OR REPLACE RESOURCE MONITOR RM_COVID_DAILY
  WITH CREDIT_QUOTA = 30
  FREQUENCY = DAILY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 75 PERCENT DO NOTIFY
           ON 85 PERCENT DO SUSPEND
           ON 95 PERCENT DO SUSPEND_IMMEDIATE;

-- 2) WAREHOUSE (small, auto-suspend & auto-resume)
CREATE OR REPLACE WAREHOUSE WH_COVID
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  RESOURCE_MONITOR = 'RM_COVID_DAILY';

-- 3) DATABASE/SCHEMA for analytics layer
CREATE OR REPLACE DATABASE DB_COVID;
USE DATABASE COVID_DB;

CREATE OR REPLACE SCHEMA COVID_DB.ANALYTICS;
USE SCHEMA ANALYTICS;